# Generated by Django 4.2.2 on 2023-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=70)),
                ('quantity', models.IntegerField(default='none')),
                ('price', models.IntegerField(default='none')),
            ],
        ),
    ]
